import type { Metadata } from "next";
import "./globals.css";
import "./styles/NavMenu.css";
import "./styles/project.css";

import BgParticle from "./components/BgParticle";
import Template from "./template/Template";
import { StoreProvider } from "./store/StoreProvider";
import Transition from "./components/Transition";
import { AnimatePresence, motion } from "framer-motion";
export const metadata: Metadata = {
  title: "Cong | Porfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Transition>
            <Template>{children}</Template>
            <BgParticle />
          </Transition>
        </StoreProvider>
      </body>
    </html>
  );
}
